baseURL       = "https://terry.wang/"
languageCode  = "en-us"
title         = "Terry Wang"
theme         = "wang"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus

  [[menu.nav]]
    name    = "ABOUT"
    url     = "about"
    weight  = 1

  [[menu.nav]]
  name    = "PORTFOLIO"
  url     = "portfolio"
  weight  = 2


  [[menu.nav]]
    name    = "CONTACT"
    url     = "contact"
    weight  = 3


# Site Params
[params]
  logo = "images/logo.svg"
  favicon ="images/favicon.png"
  dateFormat = "24 FEB 1982"

  # Meta data
  description = "Created by Terry Wang"
  keywords = "Portfolio, UX, UI, Design, 设计, 用户体验, 作品集"
  author = "Terry Wang"

  # Google Analitycs
  googleAnalitycsID = "Your ID"


  # Banner Section
  [params.banner]
    enable                = true
    background_image    = "images/"
    heading               = "<span>理清问题，</span><span>保持统一性，</span><span>富有创意，</span> <span>爱我们的用户，</span><span>带给他们美好体验</span>"
    tagline               = "WORK HARD, PLAY HARD"
    profile               = "<span>我是王珽，</span><span>UX / UI 设计师，</span><span>Web 前端工程师</span>"
    primary_button        = "简历"
    primary_button_url    = "/images/TerryWang-Resume-2022.pdf"
    secondary_button      = "联系我"
    secondary_button_url  = "contact"


  [params.showcase]
    enable    = true
    title     = "作品"


  [params.get_in_touch]
    enable    = true
    image     = "images/terry.wechat.svg"
    title     = "联系我"
    subtitle  = "LET’S WORK TOGETHER"


  [params.page404]
    enable              = true
    icon                = "images/peep.gif"
    title               = "404"
    subtitle            = "Page not found"

  [params.portfolio]
  enable    = true
  title     = "<span>清醒</span>认知，<span>清楚</span>目标，路径<span>清晰</span>，<span>倾心</span>设计，打造<span>清爽</span>体验"
  subtitle  = ""

  [params.footer]
    years = "2019-2022 "
    copyright = "Terry Wang."
