baseURL       = "http://terry.wang/"
languageCode  = "en-us"
title         = "TERRY WANG"
theme         = "wang"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "简历"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "作品"
    url     = "portfolio"
    weight  = 2
  [[menu.nav]]
    name    = "联系我"
    url     = "contact"
    weight  = 3

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "24 FEB 1982"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"


  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image    = ""
    heading               = "理清问题，保持统一性，富有创意，爱我们的用户，以极致体验为目标"
    tagline               = "WORK HARD, PLAY HARD"
    profile               = "我是王珽，UX/UI 设计师"
    primary_button        = "我的简历"
    primary_button_url    = "about"
    secondary_button      = "联系我"
    secondary_button_url  = "contact"

  [params.showcase]
    enable    = true
    title     = "作品展示"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."


  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"


  [params.page404]
    enable              = true
    icon                = "images/peep.gif"
    title               = "404"
    subtitle            = "Page not found"

  [params.footer]
    background_image    = ""
    years = "2019-2022"
    copyright = "Copyright 2019-2022 Terry.Wang All Rights Reserved."
